# Generate populated front-door config so builders can start using the solution immediately.
#
# When generate_frontdoor_config = true, Terraform writes into ./generated/ (gitignored):
#   - kiro-mcp.json            Kiro   .kiro/settings/mcp.json  (gateway HTTP mode)
#   - claude-mcp.json          Claude plugin/.mcp.json          (gateway HTTP mode)
#   - gac-frontdoor.env        the runtime/Cognito env for the local stdio bridge
#   - README-frontdoor.md      what to copy where + how to mint the token
#
# These are populated from deployment outputs (runtime ARN, region, gateway URL, Cognito ids).
# Secrets (client secret, gateway token) are NOT written — the env file names the KEYS and the
# builder fills the secret from Secrets Manager / the token helper.

locals {
  gen_dir     = "${path.module}/generated"
  gen_enabled = var.generate_frontdoor_config

  orchestrator_arn = aws_bedrockagentcore_agent_runtime.orchestrator.agent_runtime_arn

  cognito_user_pool_id = local.auth_is_cognito ? one(aws_cognito_user_pool.this[*].id) : ""
  cognito_client_id    = local.auth_is_cognito ? one(aws_cognito_user_pool_client.frontdoor[*].id) : ""

  # Kiro/Claude gateway-mode MCP config (only meaningful when a gateway is deployed).
  gateway_mcp_json = jsonencode({
    mcpServers = {
      "gac-engine" = {
        type    = "http"
        url     = "$${GAC_GATEWAY_URL}"
        headers = { Authorization = "Bearer $${GAC_GATEWAY_TOKEN}" }
      }
    }
  })

  # Local stdio bridge front-door env — KEY NAMES only for secrets (never values).
  frontdoor_env = join("\n", [
    "# Governed companion front-door env — generated by Terraform. Fill the SECRET values yourself.",
    "# Local stdio bridge (agentcore/frontdoor/mcp_bridge.py) reads these.",
    "GAC_RUNTIME_ARN=${local.orchestrator_arn}",
    "GAC_RUNTIME_REGION=${local.region}",
    local.auth_is_cognito ? "GAC_COGNITO_REGION=${local.region}" : "# GAC_COGNITO_REGION= (n/a for auth_mode=${var.auth_mode})",
    local.auth_is_cognito ? "GAC_COGNITO_USER_POOL_ID=${local.cognito_user_pool_id}" : "# GAC_COGNITO_USER_POOL_ID=",
    local.auth_is_cognito ? "GAC_COGNITO_CLIENT_ID=${local.cognito_client_id}" : "# GAC_COGNITO_CLIENT_ID=",
    "# GAC_COGNITO_CLIENT_SECRET=<from Cognito app client — do not commit>",
    "# GAC_COGNITO_USERNAME=<your test user>",
    "# GAC_COGNITO_PASSWORD=<your test user password — do not commit>",
    var.deploy_gateway ? "GAC_GATEWAY_URL=${local.gateway_url}" : "# GAC_GATEWAY_URL=<deploy_gateway=true to populate>",
    "# GAC_GATEWAY_TOKEN=<mint via agentcore/frontdoor/gateway_token.py>",
    "",
  ])
}

resource "local_file" "kiro_mcp" {
  count           = local.gen_enabled ? 1 : 0
  filename        = "${local.gen_dir}/kiro-mcp.json"
  content         = local.gateway_mcp_json
  file_permission = "0600"
}

resource "local_file" "claude_mcp" {
  count           = local.gen_enabled ? 1 : 0
  filename        = "${local.gen_dir}/claude-mcp.json"
  content         = local.gateway_mcp_json
  file_permission = "0600"
}

resource "local_file" "frontdoor_env" {
  count           = local.gen_enabled ? 1 : 0
  filename        = "${local.gen_dir}/gac-frontdoor.env"
  content         = local.frontdoor_env
  file_permission = "0600"
}

resource "local_file" "frontdoor_readme" {
  count    = local.gen_enabled ? 1 : 0
  filename = "${local.gen_dir}/README-frontdoor.md"
  content  = <<-EOT
    # Governed companion front-door config (generated)

    Generated by `terraform apply`. Auth mode: **${var.auth_mode}**.

    ## Gateway mode (recommended when deploy_gateway=true)
    1. Copy `kiro-mcp.json` to `.kiro/settings/mcp.json` (Kiro) or merge `claude-mcp.json`
       into your Claude `plugin/.mcp.json`.
    2. Export `GAC_GATEWAY_URL` (see below) and mint `GAC_GATEWAY_TOKEN` with
       `python agentcore/frontdoor/gateway_token.py`.
    - GAC_GATEWAY_URL: ${var.deploy_gateway ? local.gateway_url : "(deploy_gateway=true to populate)"}

    ## Local stdio bridge mode (direct to the runtime)
    1. Copy `gac-frontdoor.env` to `~/.gac-frontdoor.env` (chmod 600) and fill the SECRET
       values (client secret, test user/password) — they are intentionally not generated.
    2. Point your IDE at the bridge: `python agentcore/frontdoor/mcp_bridge.py`.
    - Runtime ARN: ${local.orchestrator_arn}
    - Region:      ${local.region}
    ${local.auth_is_cognito ? "- Cognito pool: ${local.cognito_user_pool_id}\n    - Cognito client: ${local.cognito_client_id}" : "- (auth_mode=${var.auth_mode}: supply your IdP client details)"}

    NEVER commit the filled env file, the client secret, or the gateway token.
  EOT

  file_permission = "0600"
}
