#!/usr/bin/env python3
"""Generate a BIBLE.md evidence corpus FROM the real knowledge base.

This is the mechanism that lets the evidence gateway be ON by default without shipping a
rival ledger (Tenet 8): the generated BIBLE.md contains one claim per knowledge file, and each
claim's `Evidence:` line points at the ACTUAL knowledge/ file and line range. When the gateway
reopens a claim, it reads the real KB file — there is no parallel copy to drift.

The corpus is DERIVED, not authored: it is regenerated from knowledge/ on demand and is
gitignored (never committed). Run it via `make bible` or directly:

    python scripts/generate_bible.py                 # writes .evidence/BIBLE.md
    python scripts/generate_bible.py --out /tmp/B.md  # custom path

Claim grammar emitted (consumed by agents/evidence_providers/bible_markdown.py):

    ## <SECTION>
    ### R-<SECTION>-<N>. <assertion>
    - Class: INVARIANT
    - Authority: AUTHORIZED
    - Evidence: <abs-path-to-real-kb-file>:1-<n>

The assertion is taken from the file's `summary`/`policy`/`description` field when present,
else the humanized file key. The class is INVARIANT for locked Tier-A files and UNSPECIFIED
otherwise; this is deliberately conservative — a human curating the corpus can refine classes.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
KNOWLEDGE_ROOT = REPO_ROOT / "knowledge"
DEFAULT_OUT = REPO_ROOT / ".evidence" / "BIBLE.md"

_SECTION_SAFE = re.compile(r"[^A-Z0-9]+")


def _section_from_key(key: str) -> str:
    """Turn a knowledge key like 'tier_a/method/design_method' into a claim-ID section token."""
    tail = key.split("/")[-1]
    return _SECTION_SAFE.sub("", tail.upper()) or "KB"


def _assertion(data: dict, key: str) -> str:
    if isinstance(data, dict):
        for field in ("summary", "policy", "description"):
            val = data.get(field)
            if isinstance(val, str) and val.strip():
                # single line, trimmed
                return " ".join(val.split())[:400]
    return f"Knowledge entry {key.split('/')[-1].replace('_', ' ')}."


def _claim_class(key: str, data: dict) -> str:
    if isinstance(data, dict) and data.get("locked") is True:
        return "INVARIANT"
    if key.startswith("tier_a/"):
        return "INVARIANT"
    return "UNSPECIFIED"


def generate(knowledge_root: Path = KNOWLEDGE_ROOT) -> str:
    sections: dict[str, list[str]] = {}
    counters: dict[str, int] = {}
    for path in sorted(knowledge_root.rglob("*.yaml")):
        rel = path.relative_to(knowledge_root)
        key = str(rel).replace(".yaml", "").replace("\\", "/")
        try:
            data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        except Exception:
            continue
        n_lines = len(path.read_text(encoding="utf-8").splitlines()) or 1
        end = min(n_lines, 12)
        section = _section_from_key(key)
        counters[section] = counters.get(section, 0) + 1
        cid = f"R-{section}-{counters[section]}"
        assertion = _assertion(data, key)
        cls = _claim_class(key, data)
        # Repo-relative path (POSIX form): the corpus is portable and carries no absolute
        # filesystem paths (which would embed the generating user's home dir — a PII/privacy
        # leak in a shared artifact). The provider resolves it against the allowed evidence
        # roots (the repo `knowledge/` tree by default), so a relative citation still resolves
        # to the real KB file. Falls back to the raw path if it is somehow outside the repo.
        try:
            rel_path = path.resolve().relative_to(REPO_ROOT).as_posix()
        except ValueError:
            rel_path = path.as_posix()
        ev = f"{rel_path}:1-{end}"
        block = [
            f"### {cid}. {assertion}",
            f"- Class: {cls}",
            "- Authority: AUTHORIZED",
            f"- Evidence: {ev}",
        ]
        sections.setdefault(section, []).append("\n".join(block))

    out = [
        "# BIBLE.md — DERIVED evidence corpus (DO NOT EDIT; DO NOT COMMIT)",
        "#",
        "# Generated by scripts/generate_bible.py from the real knowledge/ tree. Every claim's",
        "# Evidence line points at the actual KB file — this is a pointer into the knowledge base,",
        "# not a rival ledger (Tenet 8). Regenerate with `make bible` after editing knowledge/.",
        "",
    ]
    for section in sorted(sections):
        out.append(f"## {section}")
        out.append("")
        out.extend(c + "\n" for c in sections[section])
    return "\n".join(out).rstrip() + "\n"


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description="Generate the BIBLE.md evidence corpus from knowledge/")
    ap.add_argument("--out", default=str(DEFAULT_OUT), help=f"output path (default: {DEFAULT_OUT})")
    ap.add_argument("--knowledge", default=str(KNOWLEDGE_ROOT), help="knowledge root to derive from")
    args = ap.parse_args(argv)

    text = generate(Path(args.knowledge))
    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(text, encoding="utf-8")
    n_claims = text.count("\n### ")
    print(f"generate_bible: wrote {n_claims} claim(s) to {out_path}")
    print(f"  corpus root (allowed evidence root): {Path(args.knowledge).resolve()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
